# Generated by Django 2.0.5 on 2018-05-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='extension',
            field=models.CharField(default='png', max_length=10, verbose_name='extension'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(default='temp', max_length=20, verbose_name='name'),
            preserve_default=False,
        ),
    ]
