# Generated by Django 2.0.5 on 2018-05-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180519_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='name'),
        ),
    ]
