#!/bin/bash
function uploadImage {
  curl -H "Authorization: Token 5b9d9885b553c7f5f3a2caacd84467e8b1adefae" -s -F "file=@$1" http://127.0.0.1:8000/api/images
}

sleep 0.2
img="/tmp/shot.png"
gnome-screenshot -af $img
clip=$(uploadImage $img)
echo $clip | xclip -selection c
rm $img
notify-send "TnyClick $clip" -t 2000
