#!/bin/bash
function uploadImage {
  curl -H "API-ID: " -H "API-Key: " -s -F "file=@$1" http://127.0.0.1:8000/api/images/evan/
}

sleep 0.2
img="/tmp/shot.png"
gnome-screenshot -af $img
clip=$(uploadImage $img)
echo $clip | xclip -selection c
rm $img
notify-send "TnyClick $clip" -t 2000
