# Generated by Django 2.0.4 on 2018-04-23 02:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to=api.models.scramble_uploaded_filename, verbose_name='Uploaded image'),
        ),
    ]
