# Generated by Django 2.0.5 on 2018-05-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180519_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='extension'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='name'),
        ),
    ]
