# Generated by Django 2.0.4 on 2018-04-23 02:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180423_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='username',
            field=models.TextField(default='', verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to=api.models.scramble_uploaded_filename, verbose_name='image'),
        ),
    ]
