# Generated by Django 2.0.4 on 2018-04-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180423_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='username',
            field=models.CharField(max_length=100, verbose_name='username'),
        ),
    ]
